kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: k8sawsecrsecretupdater
rules:
  - apiGroups: [ "" ]
    resources: [ "secrets" ]
    verbs: [ "get", "create", "delete" ]
  - apiGroups: [ "" ]
    resources: [ "serviceaccounts" ]
    verbs: [ "get", "patch" ]
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: k8sawsecrsecretupdater
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: k8sawsecrsecretupdater
subjects:
  - kind: ServiceAccount
    name: k8sawsecrsecretupdater
roleRef:
  kind: Role
  name: k8sawsecrsecretupdater
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: batch/v1
kind: Job
metadata:
  name: k8sawsecrsecretupdater
spec:
  backoffLimit: 4
  template:
    spec:
      serviceAccountName: k8sawsecrsecretupdater
      restartPolicy: Never
      containers:
        - name: k8sawsecrsecretupdater
          image: syedalinaqi/k8s-ecr-seccret-updater:latest
          imagePullPolicy: Always
          env:
            - name: AWS_ACCOUNT
              value: "YourAwsAccountID"
            - name: AWS_ACCESS_KEY_ID
              value: YourAccessKeyID
            - name: AWS_SECRET_ACCESS_KEY
              value: YourSecretAccessKey
            - name: AWS_REGION
              value: YourRegion
            - name: SECRET_NAME
              value: SECRET_NAME
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: k8sawsecrsecretupdater
spec:
  schedule: "0 */6 * * *"
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName: k8sawsecrsecretupdater
          restartPolicy: Never
          containers:
            - name: k8sawsecrsecretupdater
              image: syedalinaqi/k8s-ecr-seccret-updater:latest
              imagePullPolicy: Always
              env:
                - name: AWS_ACCOUNT
                  value: "YourAwsAccountID"
                - name: AWS_ACCESS_KEY_ID
                  value: YourAccess
                - name: AWS_SECRET_ACCESS_KEY
                  value: YourSecretAccessKey
                - name: AWS_REGION
                  value: YourRegion
                - name: SECRET_NAME
                  value: SECRET_NAME
